#User config
Diagnostics:
  UnusedIncludes: Strict
  ClangTidy:
    Add:
    [
        performance-*,
        bugprone-*,
        modernize-*,
        clang-analyzer-*
    ]
    Remove:
      modernize-use-trailing-return-type
    CheckOptions:
      readability-identifier-naming.VariableCase: camelCase